apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: app
          image: joefastr/sample-metrics-app:latest
          ports:
            - containerPort: 3000
              name: http-metrics
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-metrics
      name: http-metrics
  selector:
    app: node-app