---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app
spec:
  jobLabel: node-app
  selector:
    matchLabels:
      app: node-app
  namespaceSelector:
    any: True
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
    # TODO add relabeling